### ISSUE TITLE
魂刃mod可能因为mod更新了，导致翻译有缺漏

### ISSUE THREAD

**Issue by Richard2038** [nixgnot/WOTR-CONTENTS-MODS-CN#10]
魂刃mod可能因为mod更新了，导致翻译有缺漏

**Comment by Richard2038** [comment]
基本集中在那些buff和部分能力名没汉化，不过影响不大
![QQ浏览器截图20230626202309](https://github.com/nixgnot/WOTR-CONTENTS-MODS-CN/assets/62453630/411a38e8-9b45-476d-af78-6dfd2ccaa0fb)
![QQ浏览器截图20230626202458](https://github.com/nixgnot/WOTR-CONTENTS-MODS-CN/assets/62453630/bd85615f-7ab1-4b38-b553-d7b3f93210e2)

**Comment by nixgnot** [comment]
> 基本集中在那些buff和部分能力名没汉化，不过影响不大 ![QQ浏览器截图20230626202309](https://user-images.githubusercontent.com/62453630/248792941-411a38e8-9b45-476d-af78-6dfd2ccaa0fb.png) ![QQ浏览器截图20230626202458](https://user-images.githubusercontent.com/62453630/248793425-bd85615f-7ab1-4b38-b553-d7b3f93210e2.png)

图上的大部分应该已经修正了
靠反编译汉化的mod就是很容易漏文本（摊手
但是Fire Focus的buff没找到，对应的描述是什么？

**Comment by Richard2038** [comment]
这MOD更新后获得灵能集中有四个版本
![QQ浏览器截图20230626214431](https://github.com/nixgnot/WOTR-CONTENTS-MODS-CN/assets/62453630/a9d0db0e-088d-44ac-82fa-ab4f0cdb557b)

**Comment by nixgnot** [comment]
> 这MOD更新后获得灵能集中有四个版本 ![QQ浏览器截图20230626214431](https://user-images.githubusercontent.com/62453630/248824235-a9d0db0e-088d-44ac-82fa-ab4f0cdb557b.png)

应该好了，应该

**Comment by nixgnot** [comment]
fixed
