### ISSUE TITLE
有几个翻译错误

### ISSUE THREAD

**Issue by ZJUZBW** [nixgnot/WOTR-CONTENTS-MODS-CN#12]
[HomebrewArchetypes](https://www.nexusmods.com/pathfinderwrathoftherighteous/mods/279)这个MOD的连锁施法，不应该是最多6次，而是2+神话阶层的使用次数。
[ExpandedContent2022](https://github.com/nixgnot/WOTR-CONTENTS-MODS-CN#ExpandedContent2022)这个MOD的观星者，灯肤座：“观星者塑造光明的力量得到了增强。观星者释放的所有带有火描述标识的法术的环级视为比正常高2级。”这里实际效果是施法者等级高2级，而不是法术环级。

**Comment by nixgnot** [comment]
收到~

**Comment by nixgnot** [comment]
> [HomebrewArchetypes](https://www.nexusmods.com/pathfinderwrathoftherighteous/mods/279)这个MOD的连锁施法，不应该是最多6次，而是2+神话阶层的使用次数。 [ExpandedContent2022](https://github.com/nixgnot/WOTR-CONTENTS-MODS-CN#ExpandedContent2022)这个MOD的观星者，灯肤座：“观星者塑造光明的力量得到了增强。观星者释放的所有带有火描述标识的法术的环级视为比正常高2级。”这里实际效果是施法者等级高2级，而不是法术环级。

收到~
不过这俩原文其实就不对2333
