### ISSUE TITLE
Psionics mod更新了，希望有空可以更新汉化

### ISSUE THREAD

**Issue by Ricahrd1016** [nixgnot/WOTR-CONTENTS-MODS-CN#24]
Psionics mod更新了，希望有空可以更新汉化

**Comment by nixgnot** [comment]
> Psionics mod更新了，希望有空可以更新汉化

看了一眼内容没有更新，只是修复了新版支持和bug，老的汉化应该可以直接继续用？

**Comment by Ricahrd1016** [comment]
但进入后发现多了个新职业和一些新法术专长

**Comment by Ricahrd1016** [comment]
![QQ浏览器截图20240402202820](https://github.com/nixgnot/WOTR-CONTENTS-MODS-CN/assets/90139724/5d8c87e4-0e6c-4776-8968-9a305238e323)

**Comment by nixgnot** [comment]
> 但进入后发现多了个新职业和一些新法术专长

已经更新，但是文本太乱了，可能有遗漏
