### ISSUE TITLE
DarkCodex汉化无效

### ISSUE THREAD

**Issue by SkyJiashu** [nixgnot/WOTR-CONTENTS-MODS-CN#3]
![WeChat截图_20230320150124](https://user-images.githubusercontent.com/44679107/226380737-819ece77-fcbb-492d-9147-80a8d722a0ea.png)

如图，汉化文件放置后汉化未生效。谢谢

**Comment by nixgnot** [comment]
> ![WeChat截图_20230320150124](https://user-images.githubusercontent.com/44679107/226380737-819ece77-fcbb-492d-9147-80a8d722a0ea.png)
> 
> 如图，汉化文件放置后汉化未生效。谢谢

 请尝试更新下dc版本，旧版id可能不一样

**Comment by nixgnot** [comment]
> > 
> 
> ![WeChat截图_20230320151322](https://user-images.githubusercontent.com/44679107/226384422-a2ed91cb-3f8c-49e0-b497-e74a4b30f55d.png)
> 
> 汉化包含mod设置选项吗？刚刚更新完之后还是不行。

不包括。选项没做多语言支持，选项请对照github上面说明调

**Comment by SkyJiashu** [comment]
> > > 
> > 
> > 
> > ![WeChat截图_20230320151322](https://user-images.githubusercontent.com/44679107/226384422-a2ed91cb-3f8c-49e0-b497-e74a4b30f55d.png)
> > 汉化包含mod设置选项吗？刚刚更新完之后还是不行。
> 
> 不包括。选项没做多语言支持，选项请对照github上面说明调

谢谢
