### ISSUE TITLE
希望提交Better Backgrounds汉化文本的修订

### ISSUE THREAD

**Issue by ShoueneKun** [nixgnot/WOTR-CONTENTS-MODS-CN#4]
我在使用您提供的Better Backgrounds的汉化文本时发现了一些错漏文本，于是进行了一些修订并把大部分语句的格式与官方文本进行了统一，希望可以提交修订后的本地化文件。

**Comment by nixgnot** [comment]
> 我在使用您提供的Better Backgrounds的汉化文本时发现了一些错漏文本，于是进行了一些修订并把大部分语句的格式与官方文本进行了统一，希望可以提交修订后的本地化文件。

可以的，感谢校对。你从这里fork一个分支，更新汉化文件，然后发pull request我来合并就行了。
不会弄的话用网盘我来更新也可以
