### ISSUE TITLE
随军神父MOD

### ISSUE THREAD

**Issue by nextentlligods** [nixgnot/WOTR-CONTENTS-MODS-CN#5]
这个mod是用不了吗？拷到Modifications下然后设置OwlcatModificationManagerSettings里添加ArsenalChaplain后无事发生啊？

**Comment by nixgnot** [comment]
> 这个mod是用不了吗？拷到Modifications下然后设置OwlcatModificationManagerSettings里添加ArsenalChaplain后无事发生啊？

这边没啥问题，如果实在搞不好的话可以用ModFinder自动安装确保路径对

**Comment by nixgnot** [comment]
fixed
