### ISSUE TITLE
ExpandedContent2022的汉化有缺漏，希望有空能修补下

### ISSUE THREAD

**Issue by Richard2038** [nixgnot/WOTR-CONTENTS-MODS-CN#6]
ExpandedContent2022的汉化有缺漏，希望有空能修补下

**Comment by nixgnot** [comment]
> 我打开了你的汉化文本略看了下，一开始里面是全汉化的，但是上了一次游戏后就冒出一些没汉化的 ![QQ浏览器截图20230524205258](https://user-images.githubusercontent.com/62453630/240623128-62eee2ba-17ee-41df-ba13-ca83193dad05.png) ![QQ浏览器截图20230524205310](https://user-images.githubusercontent.com/62453630/240623140-6d9c5f38-c6f9-4884-80f0-8f45abb08fff.png) ![QQ浏览器截图20230524213957](https://user-images.githubusercontent.com/62453630/240623146-dda7fb1d-e591-41f4-8673-7c80a9a2c5b0.png)
找到了，上个版本更新的文本漏了，应该已经修复
