### ISSUE TITLE
凤凰戏法应为需要前置

### ISSUE THREAD

**Issue by a234106261** [nixgnot/WOTR-CONTENTS-MODS-CN#7]
测试了观察了一下其他人的使用记录，凤凰戏法似乎是依赖于桌面规则调整mod存在的，但readme里写的是无前置要求
还是说有什么特殊的配置方法可以跳过这个需求？

**Comment by nixgnot** [comment]
> 测试了观察了一下其他人的使用记录，凤凰戏法似乎是依赖于桌面规则调整mod存在的，但readme里写的是无前置要求 还是说有什么特殊的配置方法可以跳过这个需求？

原MOD没有写，自己也没用这个mod。已经修改
