### ISSUE TITLE
ExpandedContent2022还继续更新汉化吗

### ISSUE THREAD

**Issue by Richard2038** [nixgnot/WOTR-CONTENTS-MODS-CN#8]
ExpandedContent2022更新了，还会更新汉化吗

**Comment by nixgnot** [comment]
> ExpandedContent2022更新了，还会更新汉化吗

不一定什么时候弄好，EC的文本实在是太恶心人了

**Comment by kuisike** [comment]
> > ExpandedContent2022更新了，还会更新汉化吗
> 
> 不一定什么时候弄好，EC的文本实在是太恶心人了

大佬，更新下expandedcontent2022的汉化吧，呜呜呜
