### ISSUE TITLE
IseKaiMod异世界主角的翻译部分字符有缺漏

### ISSUE THREAD

**Issue by a234106261** [nixgnot/WOTR-CONTENTS-MODS-CN#9]
例如法力增幅的说明文字中
任何{g | Encyclopedia：Spell}法术{/ g}造成{g | Encyclopedia：Damage}伤害
这一段应该没有空格才能正常识别，导致不能正确匹配到变量
可能还有类似的问题

题外话，readme里有一些同音错别字和词组，是不是暂时没有必要修这些无关紧要的地方

**Comment by nixgnot** [comment]
> 例如法力增幅的说明文字中 任何{g | Encyclopedia：Spell}法术{/ g}造成{g | Encyclopedia：Damage}伤害 这一段应该没有空格才能正常识别，导致不能正确匹配到变量 可能还有类似的问题
> 
> 题外话，readme里有一些同音错别字和词组，是不是暂时没有必要修这些无关紧要的地方

前条已经修复。

后面就是单纯打错了，发现可以记录一下一个个修
